name: Update Documentation
on:
  push: {}

jobs:
  update_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: rucio/rucio
          ref: master
          path: rucio
      - name: Install rucio-api generation dependencies and build markdown sites for the API
        env:
          RUCIO_TARGET_OVERRIDE: auto
          RUCIO_REPO: "https://github.com/rucio/rucio.git"
          RUCIO_BRANCH: master
        run: |
          python3 -m pip install -U pip setuptools
          python3 -m pip install -U -r requirements.txt
          docker login https://docker.pkg.github.com -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          ./rucio-generate-doc.py
          docker logout https://docker.pkg.github.com
      - name: Install dependencies and static website
        run: |
          cd website
          yarn install
          yarn build
      - name: Push to Github Pages branch
        run: |
          touch website/build/rucio-documentation/.nojekyll
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./publish.sh
